spring:
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson: 
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

app:
  blocking-coefficient: 0.9 
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:data;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:file:~/tmp/data;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: false
        
        